In [ ]:
import numpy as np 

## section- **1**

###  check if elements from following arrays return the logical value True.

In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

>use all() method

In [ ]:
for name,array in zip(list("ABCD"),[A,B,C,D]):
    print(f"{name} : {np.all(array)}")

A : True
B : False
C : False
D : True


### check if all elements from the following arrays returns the logical value True along the axis 1

In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

In [ ]:
for name,array in zip(list("ABC"),[A,B,C]):
    print(f"{name} : {np.all(array,axis=1)}")

A : [ True  True]
B : [ True False]
C : [False  True]


### check if any elements in the following arrays return the logical value True

>use any() method

In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [ ]:
for name,array in zip(list("ABCD"),[A,B,C,D]):
    print(f"{name} : {np.any(array)}")

A : False
B : True
C : True
D : True


### check if any elements in the following arrays return the logical value True along axis 0

In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [ ]:
for name,array in zip(list("ABCD"),[A,B,C,D]):
    print(f"{name} : {np.any(array,axis=0)}")

A : [False False False]
B : [False  True False]
C : [ True False False]
D : [ True False]


### check if the following array has missing data

>use isnan() method

In [ ]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

In [ ]:
print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


### check if following arrays are equal(element wise)

> use allclose() method

In [ ]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

In [ ]:
print(np.allclose(A,B))

True


### check the following arrays are equal(element wise)

> use ==

In [ ]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

In [ ]:
print(A==B)

[False False  True]


> using equal() method

In [ ]:
print(np.equal(A,B))

[False False  True]


### check which numbers from the first array is greater than the elements from second array and print 

In [ ]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

> using >

In [ ]:
print(A>B)

[ True False False False]


> using greater() method

In [ ]:
print(np.greater(A,B))

[ True False False False]


### create a 4x4 array of zeroes and print 

> use zeros() method

In [ ]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### create a 10x10 array filled with 255, set datatype to float and print

> using ones() method

In [ ]:
A=np.ones((10,10)) * 255
print(A)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


>using full() method

In [ ]:
B=np.full((10,10),fill_value=255)
print(B)

[[255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]


## section- **2**

### using numpy create a one dimensional array of all two digit numbers and print this array to the console.

>use arange() method

In [ ]:
A=np.arange(10,100)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


### using numpy, create the following array

>[[10 11 12 13 14 15 16 17 18 19]  
 [20 21 22 23 24 25 26 27 28 29]  
 [30 31 32 33 34 35 36 37 38 39]  
 [40 41 42 43 44 45 46 47 48 49]  
 [50 51 52 53 54 55 56 57 58 59]  
 [60 61 62 63 64 65 66 67 68 69]  
 [70 71 72 73 74 75 76 77 78 79]  
 [80 81 82 83 84 85 86 87 88 89]  
 [90 91 92 93 94 95 96 97 98 99]]

In [ ]:
print(np.arange(10,100).reshape(9,10))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
print(np.arange(10,100).reshape(-1,10))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
print(np.arange(10,100).reshape(9,-1))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### using nupy create a 6x6 two dimensional array-identity matrix with int datatype and print to the console

>use eye() or identity()

In [ ]:
print(np.eye(6,dtype="int"))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [ ]:
print(np.identity(6,dtype="int"))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


### set the random seed to 10, then using numpy create a one dimensional array consisting of 30 pseudo randomly generated values from the uniform distribution(0,1),print result to the console

>use rand() method

In [ ]:
np.random.seed(10)
print(np.random.rand(30))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


### using numpy create a two dimensional array with the shape (10,4) pseudo-randomly generated values from the standard normal distribution N(0,1).set the random seed to 20,print result to screen.

>use randn() method

In [ ]:
np.random.seed(20)
print(np.random.randn(10,4))

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]


### using numpy create a two dimensional array with the shape (10,4) pseudo-randomly generated values from the standard normal distribution N(100,5).set the random seed to 30,print result to screen.

In [ ]:
np.random.seed(30)
std=np.sqrt(5)
mu=100
print(std * np.random.randn(10,4)+100)

[[ 97.17349231 103.41650023  97.82942436 101.05220329]
 [ 99.7748353  100.67930221  96.14063068 103.544381  ]
 [100.30029631  97.52499594 103.52901961 100.24037271]
 [ 98.29153712  98.2666258  103.09437633 101.70027274]
 [ 99.36127721 101.20382627  95.34026547 102.09694365]
 [ 99.98708001  98.95468525  99.05410904 102.38025432]
 [ 93.50787269 103.61547679 103.18753701  98.51356237]
 [102.20256689  96.19764407  97.54000366  97.05813038]
 [101.81233513  97.66380453  98.45883627  98.09317768]
 [102.48979932  95.70413391  98.43161651 101.89861815]]


### following array is given, iterate through each item and print to console.
[[1 4 3]  
 [5 2 6]]

In [ ]:
arr1 = np.array([[1,4,3],[5,2,6]])
for i in np.nditer(arr1):
    print(i)

1
4
3
5
2
6


### using numpy create a one dimensional array of 11 equally distributed numbers from the interval [0,1]

>use linspace() method

In [ ]:
arr2 = np.linspace(0,1,11)
print(arr2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### using numpy create a one dimensional array containg the possible result from the *big lotto* game (set random seed to 42)
>result of the game is a 6 element vector of values from 1 to 49 both inclusive

In [ ]:
np.random.seed(42)
arr3 = np.random.choice(range(1,50),6)
print(arr3)

[39 29 15 43  8 21]


### using numpy create the following array
>[[0 0 0 0 0 0]  
 [0 1 0 0 0 0]  
 [0 0 2 0 0 0]  
 [0 0 0 3 0 0]  
 [0 0 0 0 4 0]  
 [0 0 0 0 0 5]]

>use diag() method

In [ ]:
diag1 = np.arange(0,6)
arr = np.zeros((6,6))
a = np.diag(diag1)
print(a)

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


## section- **3**

### using numpy create the following array.save this array to a binary file *'array.npy'* and then load back that file to another variable.print this variable to the console. 
>[[ 0  1  2  3]  
 [ 4  5  6  7]  
 [ 8  9 10 11]]  
 


>use save() and load() methods

In [ ]:
A = np.arange(12).reshape(3,-1)
np.save('Array.npy',A)


B = np.load('Array.npy')
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### using numpy create the following array.save this array to a text file *'array.txt'*  with two decimal point precision and then load back that file to another variable.print this variable to the console. 
>[[ 0  1  2  3]  
 [ 4  5  6  7]  
 [ 8  9 10 11]]  
 


>use savetxt() and loadtxt() methods

In [ ]:
A = np.array([13.652,45.433,65.5553,65.3324,787,1002])
np.savetxt('Array.txt',A,fmt='%0.2f')

B = np.loadtxt('Array.txt')
print(B)

[  13.65   45.43   65.56   65.33  787.   1002.  ]


### using numpy create the following array and convert to a list
>[[0, 1, 2, 3],  
[4, 5, 6, 7],  
[8, 9, 10, 11]]

>use tolist() method

In [ ]:
arr = np.arange(12).reshape(3,4)
a = arr.tolist()
print(a)


[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


### the following array is given, transform it to the expected output using slice operator and print to the console
>[[ 0,  1,  2,  3],  
[ 4,  5,  6,  7],  
[ 8,  9, 10, 11]]  

>expected output
>>[[ 8  9 10 11]  
 [ 4  5  6  7]  
 [ 0  1  2  3]]

In [ ]:
arr = np.arange(12).reshape(3,4)
arr[::,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

>can acheive same result using flip() too

In [ ]:
arr = np.arange(12).reshape(3,4)
np.flip(arr,axis=0)

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

### the following array is given, transform it to the expected output
>[[1. 1. 1. 1.]  
 [1. 1. 1. 1.]  
 [1. 1. 1. 1.]  
 [1. 1. 1. 1.]]  
 
 >expected output
 >>[[0. 0. 0. 0. 0. 0.]  
 [0. 1. 1. 1. 1. 0.]  
 [0. 1. 1. 1. 1. 0.]  
 [0. 1. 1. 1. 1. 0.]  
 [0. 1. 1. 1. 1. 0.]  
 [0. 0. 0. 0. 0. 0.]]  

> use pad() method

In [ ]:
arr = np.ones((4,4))
np.pad(arr,pad_width=1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### the following array is given, transform it to the expected output.
>[[0 0 0 0 0 0]  
 [0 0 0 0 0 0]  
 [0 0 0 0 0 0]  
 [0 0 0 0 0 0]  
 [0 0 0 0 0 0]  
 [0 0 0 0 0 0]]  
 
 >expected output
 >>[[10  0 10  0 10  0]  
 [ 5  0  5  0  5  0]  
 [10  0 10  0 10  0]  
 [ 5  0  5  0  5  0]  
 [10  0 10  0 10  0]  
 [ 5  0  5  0  5  0]]  

In [ ]:
A = np.zeros((6,6),dtype=np.int32)
A[::2,::2] = 10
A[1::2,::2] = 5
print(A)

        

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


In [ ]:
A = np.zeros((6,6),dtype=np.int32)
for i in range(6):
    if i%2==0:
        for j in range(6):
            if j%2==0:
                A[i,j] = 10
    else:
        for k in range(6):
            if k%2==0:
                A[i,k] = 5
print(A)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


### combine the following two arrays as one as shown and print to the console
```
A=np.arange(12).reshape(3,4)
B=np.array([[4,3,7,2],
            [0,5,2,6]]) ```
> expected output
>>[[ 0  1  2  3]  
 [ 4  5  6  7]  
 [ 8  9 10 11]  
 [ 4  3  7  2]  
 [ 0  5  2  6]]  

>use append() method

In [ ]:
A=np.arange(12).reshape(3,4)
B=np.array([[4,3,7,2],
            [0,5,2,6]])
np.append(A,B).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### the following arrays are given, extract the same elements of the arrays as a list and print to the console
```
A=np.arange(8).reshape(-1,4)
B=np.array([[9,10,11,3],
            [2,8,0,9]])
            ```

>use intersect1d() method

In [ ]:
A=np.arange(8).reshape(-1,4)
B=np.array([[9,10,11,3],
            [2,8,0,9]])
print(np.intersect1d(A,B))

[0 2 3]


### the following array is given, extract all the unique values and print to the console.

>use unique() method

In [ ]:
np.random.seed(10)
A = np.random.randint(low=1, high=10, size=(3, 5))
print(A)

[[5 1 2 1 2]
 [9 1 9 7 5]
 [4 1 5 7 9]]


In [ ]:
print(np.unique(A))

[1 2 4 5 7 9]


### the following array is given, return a list of indexes with maximum values for each row from this array and print to the console

>[[0.4 0.3 0.3]  
 [0.1 0.1 0.8]  
 [0.2 0.5 0.3]]

>use argmax() method

In [ ]:
A = np.array([[0.4, 0.3, 0.3],
[0.1, 0.1, 0.8],
[0.2, 0.5, 0.3]])
np.argmax(A,axis=0)

array([0, 2, 1], dtype=int64)

## section- **4**

### the following array is given, sort this array
1.by row(ascending)  
2.by coloumn(ascending)

>[[ 4.99,  3.49,  9.99],  
       [ 1.99,  9.99,  4.99],  
       [14.99,  2.39,  7.29]]  

In [ ]:
A = np.array([[ 4.99, 3.49, 9.99],
[ 1.99, 9.99, 4.99],
[14.99, 2.39, 7.29]])
B = np.sort(A)
print(B)
C = np.sort(B)

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]


### extract all the elements greater than 8 from the following array and print the result to console
>[[ 4.99,  3.49,  9.99],  
       [ 1.99,  9.99,  4.99],  
       [14.99,  2.39,  7.29]]  

>use where() method

In [ ]:
a = np.array([[ 4.99, 3.49, 9.99],
[ 1.99, 9.99, 4.99],
[14.99, 2.39, 7.29]])
np.where(a>8,a,False)

array([[ 0.  ,  0.  ,  9.99],
       [ 0.  ,  9.99,  0.  ],
       [14.99,  0.  ,  0.  ]])

### the following array is given, replace the values which are greater than 10, with a fixed value *10.0* and print the array to the screen
>[[4.99, 3.49, 9.99],  
              [1.99, 9.99, 14.99],  
              [14.99, 2.39, 7.29]]

In [ ]:
b = np.array([[4.99, 3.49, 9.99],
            [1.99, 9.99, 14.99],
            [14.99, 2.39, 7.29]])
b[b>10]=10.0
print(b)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


>same result can be acheived with where() method

In [ ]:
np.where(b>10,10.0,b)


array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 10.  ],
       [10.  ,  2.39,  7.29]])

### tranform the following array as a 1D array and print to the screen
>[[4.99, 3.49, 9.99],  
              [1.99, 9.99, 14.99],  
              [14.99, 2.39, 7.29]]

>use ravel() method

In [ ]:
z= np.array([[4.99, 3.49, 9.99],
[1.99, 9.99, 14.99],
[14.99, 2.39, 7.29]])
np.ravel(z)

array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])

>use flatten() method of ndarray

In [ ]:
z.flatten()

array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])

>use -1 as the shape

In [ ]:
z[:-1,:-1]

array([[4.99, 3.49],
       [1.99, 9.99]])

### the following array is given, using numpy create an array of same shape and datatype and fill it with zeros and print to the console.
>[[4.99, 3.49, 9.99],  
              [1.99, 9.99, 14.99],  
              [14.99, 2.39, 7.29]]

>use zeros_like() method

In [ ]:
a = np.array([[4.99, 3.49, 9.99],
[1.99, 9.99, 14.99],
[14.99, 2.39, 7.29]])
print(np.zeros_like(a))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


>use slice operator

In [ ]:
a[:] = 0.
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
